import { NextResponse } from "next/server"

export const dynamic = "force-dynamic"

export function GET() {
  const html = [
    '<!DOCTYPE html>',
    '<html lang="pt-BR">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    '<title>Guia de Uso - DOOHPLAY</title>',
    '<style>',
    '* { margin:0; padding:0; box-sizing:border-box; }',
    'body { font-family:system-ui,sans-serif; background:#0F172A; color:#F1F5F9; min-height:100vh; }',
    '.header { background:#1E293B; padding:40px 24px; text-align:center; border-bottom:1px solid #334155; }',
    '.logo { font-size:28px; font-weight:900; color:#F9FAFB; margin-bottom:16px; }',
    '.logo span { color:#3B82F6; }',
    'h1 { font-size:22px; font-weight:700; margin-bottom:8px; }',
    '.sub { font-size:14px; color:#94A3B8; }',
    '.container { max-width:680px; margin:0 auto; padding:32px 24px; }',
    '.section { margin-bottom:36px; }',
    '.section-title { font-size:12px; font-weight:700; color:#3B82F6; text-transform:uppercase; letter-spacing:1px; margin-bottom:20px; }',
    '.step { display:flex; gap:14px; margin-bottom:18px; }',
    '.num { width:28px; height:28px; border-radius:50%; background:#3B82F6; color:white; font-size:13px; font-weight:700; display:flex; align-items:center; justify-content:center; flex-shrink:0; margin-top:2px; }',
    '.content { flex:1; }',
    '.step-title { font-size:15px; font-weight:600; color:#F1F5F9; margin-bottom:4px; }',
    '.step-desc { font-size:13px; color:#94A3B8; line-height:1.6; }',
    '.step-desc b { color:#F1F5F9; }',
    '.feature { background:#1E293B; border:1px solid #334155; border-radius:12px; padding:20px; margin-bottom:16px; }',
    '.feature-title { font-size:16px; font-weight:700; color:#F1F5F9; margin-bottom:10px; }',
    '.feature-desc { font-size:14px; color:#94A3B8; line-height:1.8; }',
    '.feature-desc b { color:#F1F5F9; }',
    '.grid { display:grid; grid-template-columns:1fr 1fr; gap:12px; }',
    '.card { background:#1E293B; border:1px solid #334155; border-radius:10px; padding:16px; }',
    '.card-icon { font-size:24px; margin-bottom:8px; }',
    '.card-title { font-size:14px; font-weight:700; color:#F1F5F9; margin-bottom:4px; }',
    '.card-desc { font-size:12px; color:#64748B; line-height:1.5; }',
    '.url-box { background:#0F172A; border:1px solid #334155; border-radius:8px; padding:12px 16px; margin-top:10px; font-family:monospace; font-size:13px; color:#3B82F6; }',
    '.tip { background:#0F172A; border-left:3px solid #3B82F6; border-radius:8px; padding:12px 14px; margin-top:10px; font-size:13px; color:#94A3B8; line-height:1.6; }',
    '.divider { height:1px; background:#1E293B; margin:28px 0; }',
    '.contact { background:#1E293B; border-radius:12px; padding:24px; text-align:center; }',
    '.contact h3 { font-size:16px; font-weight:700; margin-bottom:8px; }',
    '.contact p { font-size:14px; color:#94A3B8; line-height:1.6; }',
    '.contact a { color:#3B82F6; text-decoration:none; }',
    '@media(max-width:480px){ .grid { grid-template-columns:1fr; } }',
    '</style>',
    '</head>',
    '<body>',
    '<div class="header">',
    '<div class="logo">DOOH<span>PLAY</span></div>',
    '<h1>Guia de Uso do Sistema</h1>',
    '<p class="sub">Tudo que voce precisa saber para gerenciar sua TV</p>',
    '</div>',
    '<div class="container">',

    '<div class="section">',
    '<div class="section-title">Como acessar o sistema</div>',
    '<div class="step"><div class="num">1</div><div class="content"><div class="step-title">Abra o link do seu dashboard</div><div class="step-desc">Acesse pelo celular ou computador:</div><div class="url-box">doohplay.com.br/dashboard/local/SEU-CODIGO</div></div></div>',
    '<div class="step"><div class="num">2</div><div class="content"><div class="step-title">Faca login com WhatsApp ou Email</div><div class="step-desc">Informe seu <b>telefone</b> ou <b>email</b> cadastrado. Voce recebe um codigo de verificacao — sem senha!</div></div></div>',
    '<div class="step"><div class="num">3</div><div class="content"><div class="step-title">Salve nos favoritos</div><div class="step-desc">Salve o link para acessar rapidamente sempre que precisar.</div></div></div>',
    '</div>',

    '<div class="divider"></div>',

    '<div class="section">',
    '<div class="section-title">O que voce ve no painel principal</div>',
    '<div class="grid">',
    '<div class="card"><div class="card-icon">📺</div><div class="card-title">Status da TV</div><div class="card-desc">Mostra se sua TV esta Online ou Offline em tempo real</div></div>',
    '<div class="card"><div class="card-icon">💰</div><div class="card-title">Receita do mes</div><div class="card-desc">Quanto voce esta ganhando com anuncios na sua TV</div></div>',
    '<div class="card"><div class="card-icon">📊</div><div class="card-title">Visualizacoes</div><div class="card-desc">Quantas vezes os anuncios foram exibidos na tela</div></div>',
    '<div class="card"><div class="card-icon">📣</div><div class="card-title">Campanhas ativas</div><div class="card-desc">Quantos anunciantes estao aparecendo na sua TV</div></div>',
    '</div>',
    '</div>',

    '<div class="divider"></div>',

    '<div class="section">',
    '<div class="section-title">Como enviar conteudo para a TV</div>',
    '<div class="step"><div class="num">1</div><div class="content"><div class="step-title">Clique em Conteudo no menu</div><div class="step-desc">No painel lateral, clique em <b>Conteudo</b></div></div></div>',
    '<div class="step"><div class="num">2</div><div class="content"><div class="step-title">Clique em + Enviar midia</div><div class="step-desc">Botao azul no canto superior direito</div></div></div>',
    '<div class="step"><div class="num">3</div><div class="content"><div class="step-title">Selecione o arquivo</div><div class="step-desc">Escolha imagem (JPG, PNG, WEBP) ou video (MP4)</div><div class="tip">Tamanho recomendado: 1920x1080px (Full HD)</div></div></div>',
    '<div class="step"><div class="num">4</div><div class="content"><div class="step-title">Aparece na TV automaticamente!</div><div class="step-desc">Em segundos o conteudo ja aparece na sua TV</div></div></div>',
    '</div>',

    '<div class="divider"></div>',

    '<div class="section">',
    '<div class="section-title">Gerenciar ordem e horario</div>',
    '<div class="feature">',
    '<div class="feature-title">Aba Playlist</div>',
    '<div class="feature-desc">',
    '• <b>Reordenar</b> midias — arraste para mudar a ordem<br>',
    '• <b>Definir o tempo</b> de cada imagem (padrao: 15 segundos)<br>',
    '• <b>Agendar por horario</b> — ex: promocao de almoco das 11h as 14h<br>',
    '• <b>Agendar por dia</b> — ex: promocao de sexta so na sexta-feira<br>',
    '• <b>Calendario semanal</b> — veja toda a programacao de uma vez',
    '</div>',
    '</div>',
    '</div>',

    '<div class="divider"></div>',

    '<div class="section">',
    '<div class="section-title">Monitorar sua TV</div>',
    '<div class="feature">',
    '<div class="feature-title">Aba Minha TV</div>',
    '<div class="feature-desc">',
    '• <b>Status Online/Offline</b> em tempo real<br>',
    '• <b>Qualidade do sinal</b> Wi-Fi<br>',
    '• <b>Temperatura</b> do dispositivo<br>',
    '• <b>Uptime</b> — ha quanto tempo a TV esta ligada<br>',
    '• <b>Playlist em execucao</b> — o que esta rodando agora',
    '</div>',
    '</div>',
    '<div class="tip">Se a TV aparecer Offline, verifique se o dispositivo esta ligado e conectado ao Wi-Fi. Atualiza automaticamente a cada 30 segundos.</div>',
    '</div>',

    '<div class="divider"></div>',

    '<div class="section">',
    '<div class="section-title">Dicas para aproveitar mais</div>',
    '<div class="step"><div class="num">💡</div><div class="content"><div class="step-title">Mantenha a TV sempre ligada</div><div class="step-desc">Quanto mais tempo online, mais visualizacoes — e mais voce ganha.</div></div></div>',
    '<div class="step"><div class="num">💡</div><div class="content"><div class="step-title">Use imagens no tamanho certo</div><div class="step-desc">Imagens em <b>1920x1080px</b>. Use o Canva (gratis) para criar artes.</div></div></div>',
    '<div class="step"><div class="num">💡</div><div class="content"><div class="step-title">Programe com antecedencia</div><div class="step-desc">Agende promocoes de fim de semana e datas especiais com antecedencia.</div></div></div>',
    '</div>',

    '<div class="contact">',
    '<h3>Precisa de ajuda?</h3>',
    '<p>WhatsApp: <a href="https://wa.me/5511999999999">(11) 9 9999-9999</a><br>',
    'Email: <a href="mailto:suporte@doohplay.com.br">suporte@doohplay.com.br</a><br>',
    'Acesse: <a href="https://doohplay.com.br">doohplay.com.br</a></p>',
    '</div>',

    '</div>',
    '</body>',
    '</html>'
  ].join('\n')

  return new NextResponse(html, {
    headers: { 'Content-Type': 'text/html; charset=utf-8' }
  })
}
