/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mdlbajgnntjwhycouzit"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kbGJhamdubnRqd2h5Y291eml0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2MTM0NTgsImV4cCI6MjA4MjE4OTQ1OH0.yb31JXsrW24TqvqA6WEUXCafdh-cPNjwb-q382JAscQ"
