export const LogEventType = {
  CAMPAIGN_STARTED: "CAMPAIGN_STARTED",
  CAMPAIGN_FINISHED: "CAMPAIGN_FINISHED",

  EXECUTION_STARTED: "EXECUTION_STARTED",
  EXECUTION_FINISHED: "EXECUTION_FINISHED",
  EXECUTION_FAILED: "EXECUTION_FAILED",

  PLAYER_ONLINE: "PLAYER_ONLINE",
  PLAYER_OFFLINE: "PLAYER_OFFLINE",
} as const;

export type LogEventType =
  typeof LogEventType[keyof typeof LogEventType];

export const LOG_EVENT_TYPES = LogEventType
